# Generated by Django 5.1.7 on 2025-06-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
